---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-listener
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-sa
  serviceType: ClusterIP
  triggers:
    - template:
        name: microservice-ci-trigger
      bindings:
      - name: admin-ci
      - name: cart-ci
      - name: comment-ci
      - name: delivery-status-ci
      - name: order-ci
      - name: payment-info-ci
      - name: point-ci
      - name: product-ci
      - name: rate-ci
      - name: search-ci
      - name: user-ci
      interceptors:
        - cel:
            filter: "body.ref.startsWith('refs/heads/develop')"
        - github:
            secretRef:
              secretName: github-webhook-credentials
              secretKey: github-webhook-secret
              namespace: tekton-pipelines
            eventTypes:
              - push
---
