---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: microservice-ci-trigger-binding
  namespace: tekton-pipelines
spec:
  params:
    - name: GIT_REPO_URL
      value: "$(body.repository.url)"
    - name: COMMIT_HASH
      value: $(body.head)
      # value: $(body.after)
    - name: MICROSERVICE
      value: comment
---
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-credentials
  namespace: tekton-pipelines
type: Opaque
stringData:
  github-webhook-secret: please-modify-for-high-security-here
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-listener
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-sa
  triggers:
    - template:
        name: microservice-ci-trigger
      bindings:
      - name: microservice-ci-trigger-binding
      interceptors:
        - github:
            secretRef:
              secretKey: github-webhook-credentials
              secretName: github-webhook-secret
              namespace: tekton-pipelines
            eventTypes:
              - push

