---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-credentials
  namespace: tekton-pipelines
  annotations:
    tekton.dev/docker-0: https://registry-harbor-core.infra.svc.cluster.local/v2/
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: admin
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-sa
  namespace: tekton-pipelines
spec:
secrets:
- name: harbor-credentials
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: kaniko-build-and-push
  namespace: tekton-pipelines
spec:
  inputs:
    params:
    - name: DOCKERFILE
      description: Path to the Dockerfile to build.
      default: ./Dockerfile
    - name: CONTEXT
      description: The build context used by Kaniko.
      default: ./
    - name: EXTRA_ARGS
      default: ""
    - name: BUILDER_IMAGE
      description: The image on which builds will run
      default: gcr.io/kaniko-project/executor:v0.13.0
    resources:
    - name: source-repo
      type: git
  outputs:
    resources:
    - name: image-repo
      type: image
  steps:
  - name: build-and-push
    workingdir: /workspace/source-repo
    image: $(inputs.params.BUILDER_IMAGE)
    # specifying DOCKER_CONFIG is required to allow kaniko to detect docker credential
    # https://github.com/tektoncd/pipeline/pull/706
    env:
    - name: DOCKER_CONFIG
      value: /tekton/home/.docker
    command:
    - /kaniko/executor
    - $(inputs.params.EXTRA_ARGS)
    - --dockerfile=$(inputs.params.DOCKERFILE)
    - --context=/workspace/source-repo/$(inputs.params.CONTEXT)
    - --destination=$(outputs.resources.image-repo.url)
    - --cache=true
    - --insecure
    - --skip-tls-verify
    securityContext:
      runAsUser: 0
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: pull-request-manifest
  namespace: tekton-pipelines
spec:
  inputs:
    params:
    - name: MICROSERVICE
      default: somemicroservice 
    resources:
    - name: source-repo
      type: git
  steps:
  - name: pull-request-manifest
    workingdir: /workspace/source-repo
    image: centos:8
    command:
    - cat
    - /workspace/source-repo/microservices/$(inputs.params.MICROSERVICE)/main.go
    securityContext:
      runAsUser: 0
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: ci
  namespace: tekton-pipelines
spec:
  resources:
    - name: source-repo
      type: git
    - name: image-repo
      type: image
  params:
  - name: MICROSERVICE
    default: somemicroservice
  tasks:
  - name: build-and-push
    taskRef:
      name: kaniko-build-and-push
    params:
    - name: DOCKERFILE
      value: ./microservices/$(params.MICROSERVICE)/Dockerfile
    - name: CONTEXT
      value: ./microservices/$(params.MICROSERVICE)
    resources:
      inputs:
      - name: source-repo
        resource: source-repo
      outputs:
      - name: image-repo
        resource: image-repo
  - name: pull-request-manifest
    taskRef:
      name: pull-request-manifest
    runAfter:
    - build-and-push
    params:
    - name: MICROSERVICE
      value: $(params.MICROSERVICE)
    resources:
      inputs:
      - name: source-repo
        resource: source-repo
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: microservice-ci-trigger
  namespace: tekton-pipelines
spec:
  params:
    - name: GIT_REPO_URL
      description: The git repository url
      default: https://github.com/kubernetes-native-testbed/kubernetes-native-testbed
    - name: MICROSERVICE
      default: somemicroservice
    - name: COMMIT_HASH
      description: GitHub commit hash
      default: xxxxxxxx
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: source-repo-$(params.MICROSERVICE)-$(params.COMMIT_HASH)
      namespace: tekton-pipelines
    spec:
      type: git
      params:
        - name: revision
          value: $(params.COMMIT_HASH)
        - name: url
          value: $(params.GIT_REPO_URL)
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: image-repo-$(params.MICROSERVICE)-$(params.COMMIT_HASH)
      namespace: tekton-pipelines
    spec:
      type: image
      params:
        - name: url
          value: registry-harbor-core.infra.svc.cluster.local/library/$(params.MICROSERVICE):$(params.COMMIT_HASH)
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      name: ci-$(params.MICROSERVICE)-$(params.COMMIT_HASH)-$(uid)
      namespace: tekton-pipelines
    spec:
      serviceAccountName: tekton-sa
      timeout: 1h0m0s
      pipelineRef:
        name: ci
      params:
        - name: MICROSERVICE
          value: $(params.MICROSERVICE)
        - name: COMMIT_HASH
          value: $(params.COMMIT_HASH)
      resources:
        - name: source-repo
          resourceRef:
            name: source-repo-$(params.MICROSERVICE)-$(params.COMMIT_HASH)
        - name: image-repo
          resourceRef:
            name: image-repo-$(params.MICROSERVICE)-$(params.COMMIT_HASH)
---
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-credentials
  namespace: tekton-pipelines
type: Opaque
stringData:
  github-webhook-secret: please-modify-for-high-security-here
---
