---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-issuer
  namespace: infra
spec:
  acme:
    email: amsy810@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-account-key
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: testbed.34.84.105.184.xip.io
  namespace: infra
spec:
  secretName: testbed-cert
  issuerRef:
    name: letsencrypt-issuer
  dnsNames:
  - testbed.34.84.105.184.xip.io
  - argocd.34.84.105.184.xip.io
  commonName: testbed.34.84.105.184.xip.io
