---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-info
  namespace: payment-info
  labels:
    service: payment-info
    role: app
spec:
  replicas: 3
  selector:
    matchLabels:
      service: payment-info
      role: app
  template:
    metadata:
      labels:
        service: payment-info
        role: app
    spec:
      containers:
        - name: payment-info-app
          image: registry-harbor-core.infra.svc.cluster.local/library/payment-info:1ea51ec8dff5fdadda280861d31b139812355299
          env:
          - name: DB_HOST
            value: 127.0.0.1
          - name: DB_PORT
            value: "6443"
          - name: DB_USERNAME
            value: root
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: payment-info-db
                key: password
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: payment-info
  namespace: payment-info
  labels:
    service: payment-info
    role: app
spec:
  type: ClusterIP
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8080
      targetPort: 8080
  selector:
    service: payment-info
    role: app
