apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: payment-info-db
  namespace: payment-info
  labels:
    service: payment-info
    role: db
spec:
  dockerImage: registry.opensource.zalan.do/acid/spilo-cdp-12:1.6-p16
  teamId: "payment-info"
  volume:
    size: 10Gi
    storageClass: rook-ceph-block
  numberOfInstances: 3
  users:
    payment-info-user:
    - superuser
    - createdb
  enableMasterLoadBalancer: false
  enableReplicaLoadBalancer: false
  databases:
    payment_info_db: payment-info-user
  postgresql:
    version: "11"
    parameters: # Expert section
      shared_buffers: "32MB"
      max_connections: "10"
      log_statement: "all"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  patroni:
    initdb:
      encoding: "UTF8"
      locale: "en_US.UTF-8"
      data-checksums: "true"
    ttl: 30
    loop_wait: &loop_wait 10
    retry_timeout: 10
    maximum_lag_on_failover: 33554432


