---
apiVersion: v1
kind: Secret
metadata:
  name: payment-info-db
  namespace: payment-info
data:
  password: cGF5bWVudEluZm8=
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: payment-info-db-config
data:
  my.cnf: |-
    [mysqld]
    default_authentication_plugin=mysql_native_password
---
apiVersion: mysql.oracle.com/v1alpha1
kind: Cluster
metadata:
  name: payment-info-db
  namespace: payment-info
spec:
  multiMaster: true
  members: 3
  config:
    name: mysql-config
  rootPasswordSecret:
    name: payment-info-db
  resources:
    agent:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 300m
        memory: 128Mi
    server:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 512Mi
  volumeClaimTemplate:
    metadata:
      name: data
    spec:
      storageClassName: rook
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
