---
apiVersion: skaffold/v2alpha3
kind: Config
build:
  artifacts:
  - image: local-point
    docker:
      dockerfile: ./Dockerfile
  tagPolicy:
    envTemplate:
      template: "local-point:latest"
  local:
    push: false
deploy:
  kustomize:
    paths:
    - ../../development/point
    buildArgs:
    - --load_restrictor
    - LoadRestrictionsNone
    flags:
      delete:
      - --force
      - --grace-period=0
      - --wait
