---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: harbor
  namespace: infra
  labels:
    service: harbor
    role: proxy
spec:
  routes:
    - services:
        - name: harbor
          port: 80
      permitInsecure: true
