---
apiVersion: v1
kind: Secret
metadata:
  name: user-db
  namespace: user
  labels:
    service: user
    role: db
type: Opaque
stringData:
  ROOT_PASSWORD: user
  DATABASE: user
  USER: user
  PASSWORD: user
---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: user-db
  namespace: user
  labels:
    service: user
    role: db
spec:
  replicas: 2
  secretName: user-db
  mysqlVersion: "5.7"
  minAvailable: "10%"
  podSpec:
    persistentVolumeClaim:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: rook-ceph-block
      resources:
        requests:
          storage: 10Gi
---
