---
apiVersion: v1
kind: Secret
metadata:
  name: user-db
  namespace: user
  labels:
    service: user
    role: db
type: Opaque
data:
  ROOT_PASSWORD: cHJvZHVjdA==
  DATABASE: cHJvZHVjdA==
  USER: cHJvZHVjdA==
  PASSWORD: cHJvZHVjdA==
---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: user-db
  namespace: user
  labels:
    service: user
    role: db
spec:
  replicas: 2
  secretName: user-db
  mysqlVersion: "5.7"
  minAvailable: "10%"
  podSpec:
    persistentVolumeClaim:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: rook-ceph-block
      resources:
        requests:
          storage: 4Gi
---
