---
apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  name: comment-db
  namespace: comment
  labels:
    service: comment
    role: db
spec:
  version: "4.1"
  storageType: Durable
  storage:
    storageClassName: "rook"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 3Gi
  databaseSecret:
    secretName: comment-db-auth
  terminationPolicy: DoNotTerminate

---
apiVersion: v1
kind: Secret
metadata:
  name: comment-db-auth
  namespace: comment
  labels:
    service: comment
    role: db
type: Opaque
data:
  password: Y29tbWVudA==
  username: Y29tbWVudA==
