---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: comment
  namespace: comment
spec:
  routes:
    - services:
        - name: comment
          port: 8080
      permitInsecure: true
