---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: delivery-status
  namespace: delivery-status
spec:
  routes:
    - services:
        - name: delivery-status
          port: 8080
