---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: namespace-delegation-root
  namespace: infra
  labels:
    service: infra
    role: proxy
spec:
  virtualhost:
    fqdn: testbed.amsy.dev
    tls:
      secretName: tls-cert 
  includes:
  # delegate the subpath, `/product` to the HTTPProxy object in the product namespace with the name `product`
  - name: product
    namespace: product
    conditions:
    - prefix: /product
  - name: payment-info
    namespace: payment-info
    conditions:
    - prefix: /payment-info
  - name: user
    namespace: user
    conditions:
    - prefix: /user
  - name: delivery-status
    namespace: delivery-status
    conditions:
    - prefix: /delivery-status
  - name: comment
    namespace: comment
    conditions:
    - prefix: /comment
  - name: order
    namespace: order
    conditions:
    - prefix: /order
  - name: rate
    namespace: rate
    conditions:
    - prefix: /rate
  - name: cart
    namespace: cart
    conditions:
    - prefix: /cart
  - name: point
    namespace: point
    conditions:
    - prefix: /point
  - name: search
    namespace: search
    conditions:
    - prefix: /search
  - name: admin
    namespace: admin
    conditions:
    - prefix: /admin
  routes:
    - services:
        - name: default-http-backend
          port: 8080
      permitInsecure: true
---
# openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout ~/tls.key -out ~/tls.crt -subj "/CN=testbed.amsy.dev"
# kubectl create secret tls --save-config  --key ~/tls.key --cert ~/tls.crt tls-cert -o yaml --dry-run
apiVersion: v1
kind: Secret
metadata:
  name: tls-cert
  namespace: infra
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNzakNDQVpvQ0NRQ0NEN1I3L1FLNXl6QU5CZ2txaGtpRzl3MEJBUXNGQURBYk1Sa3dGd1lEVlFRRERCQjAKWlhOMFltVmtMbUZ0YzNrdVpHVjJNQjRYRFRJd01ERXlOREUzTURFeU4xb1hEVEl4TURFeU16RTNNREV5TjFvdwpHekVaTUJjR0ExVUVBd3dRZEdWemRHSmxaQzVoYlhONUxtUmxkakNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFECmdnRVBBRENDQVFvQ2dnRUJBTnNVaUhEQXNDUURzcUd2TDZ5bERxOENKR0lLUWVGUTl6RVZqR3ZWaS82WUgyZS8KdW91MWllMENUUXlXYjl5aHB3SkhlbHFpRGY1Y2hUSFI3NlM1SmQ1UHpDVjI0b2Nad2c0V29NazlGOVFYVGx1KworLzlVc3JLampyTmtwcHRmVStMSnVDeS9NRENTOEZSN3FNa1RJdUdOVHh5UGpnL3RSeFVEeTFsbG1PR2hXOG9uCjZERjhvakJUcGhIR3BvS2xxRTd3bHdqWmFETTFXelNRb2pwZjBLUkhmM0FqSERzWHZ5NE1GM1NqS3VRZHcyc2sKMHVUWTZqQlRGQkJwb0xCdGtuYnJucVR2MnhycDZlVkwvNkRxeVcyTmkzTHNWVFlIUU9LcThQY0JkV0VXYXI2YQpDSW9zRlU5dUlERFd3ek9GbzhZWmFKRU9URnRXVFhhTi9OMUwrMUVDQXdFQUFUQU5CZ2txaGtpRzl3MEJBUXNGCkFBT0NBUUVBcHEvUmRQRzdvN21hMTNVSnJkRUtIQkp1WEoydkdjN1dieGEycUczNXQyQ1N2L3VLd3E3RFl1OW4KVlJLdUQxOGVkSDhGODRXcEc5SjVrUVBZaENkNHFmdFdTdnpEZStEY2N3c3hZdDRtTHBMR05LeEt3NjNOVXpLZQowNnNaakJ4R3BlR1VqNWZ2NEEzYVMrNmg4SUJPN3MvbmtNQit5am9Eak9yZWxCQmNHaHlWUXZpRmtjbGI3UUk5CjhVN0kxS29taWVXMHJ2ZHhGRktBYW40dEErSlRMWkFQQ0tWRWY0elF3KzY5UmRUK0xmQllCekFnV3Y5dElGVWwKZGNXaVFnUHY1UHVRN2psRXM3VlpvcGtkWVF6SDFBS2hOU1k5bXBnQUM0cjhJM09lb0krS0o1NmJrQnVPSDE5agpLakhnbFBnc1Rhc1d3bnIxbksvQmZTaEJDenlpYVE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRRGJGSWh3d0xBa0E3S2gKcnkrc3BRNnZBaVJpQ2tIaFVQY3hGWXhyMVl2K21COW52N3FMdFludEFrME1sbS9jb2FjQ1IzcGFvZzMrWElVeAowZStrdVNYZVQ4d2xkdUtIR2NJT0ZxREpQUmZVRjA1YnZ2di9WTEt5bzQ2elpLYWJYMVBpeWJnc3Z6QXdrdkJVCmU2akpFeUxoalU4Y2o0NFA3VWNWQTh0WlpaamhvVnZLSitneGZLSXdVNllSeHFhQ3BhaE84SmNJMldnek5WczAKa0tJNlg5Q2tSMzl3SXh3N0Y3OHVEQmQwb3lya0hjTnJKTkxrMk9vd1V4UVFhYUN3YlpKMjY1Nms3OXNhNmVubApTLytnNnNsdGpZdHk3RlUyQjBEaXF2RDNBWFZoRm1xK21naUtMQlZQYmlBdzFzTXpoYVBHR1dpUkRreGJWazEyCmpmemRTL3RSQWdNQkFBRUNnZ0VBU3c2VTFEUmY1R2JUNjJydXBYS0RQbGc0aU5KRTBlSUFYbk9vZ1VWUFNqRnEKQ1F4NTUrV1JWSDhHVUxxMXBseEhzSk0yaXhpY1BMb0w5QTZkME15UitjRlRDcjdaU3puNjd3SzNvVnBwOElMdgptS1V0QnNSSTJNVUtYZEdzOXV4SS9CanFIWUovQ3hVOGUyVkdaV1ZGL1FxQndTSTVwS0ZCU2lUYnBVd1dmYTQ5CkhaZjVvR01wZWZiaDNZN0hHSlBIZXFVUUtyb2MvMDBlL0FNc1hFdFdwQWhMdVVTSmFMMWdHbGRTSlVweWJ5cmcKYmNlSjFUMHFFSjVib2JSZ3pnZkVFTGkxYzBUZ082SFM4aDA4WEltSGdhOUZCcjAzTFRvYkdyaFFvNCtUdEVnYQpLZVZxbUNpL3NRcmVUdEpjMG9XZENXb3dMK2pxN0NGWEFhNEhjdzROOVFLQmdRRDVNb25COTJqVTJQdkZ1d3dWCjAyNmF2Z1ErVFNBWWhpRnJTbWhiWEN3ZUtDRFNNZlBtaDlHRHBScTJ3KyswYnFXVUl1ektRNnVYY1Vybm5FNCsKcWN5UmtjOHc3TFZwMWRxcENDWkNIYk1DbEl3ZmFtQ0tuR1R1bkxySDAxalNnU1ZHdGNjM3Zybk5lQnhYaDlUegpFL1VJUXdZd3pydmFnSVdDcVhPcURldnRyd0tCZ1FEaEQ0YjlmQjRvQkVGNVlKdExaNEFkSDl2Y3I3UVIxRUNkCjQ5eWlaL0t5akpUZFVTZFlxbk8wTTRSdURxMTM5K0NhNTlwYzFUbXd4Q2huTVovSXFJeEFZb2Y2VmZSSVlMc0kKM0NSYThzaWlMWDV4bTlGVXFERFFraFdvRFVaaXV5UEsvOXJ3ZVNKbkcwMEFxQzJ6cDZOUHBUNDZxbFQzWnEwTAo4REpQbXZIbS93S0JnRzlUa3BOaTBpUjBvMVhja0RPWDkwdU9KQnNwSFhPWFNJckQvUWNEa0hvUWQwa3dJOFFUClhSZ3d4RlJ1Q0VKVlJBZC82c1Vab2lqUDVpUytnWDRoSVZEUEVQN01ZT2RkTUloZkthaFQyRXNJemVpaS8yb3QKSURJeE5vaGE5TTFtQUo4c1NrbXZIUmFiMkIyS2d5bnMrb1NzWExHbFNlcjlpNmVweUJCcWs4SGxBb0dBSE9pRApyRmVmQUFEYjhCMUtsVHJzSjlHSnlpVC9lakxMUWZ5Y3dIZWRvdldQd1lYRkNneUs1Q0NoNkFrV213eEoyMXZnCm5uLzg4d21mTHZJZTFnVmdUbnpaZm53LzduUU9VaXNFdUhIcTkzbmtmZTlIeWhuNGV6SG9lamVLVFBCQXZyaHkKaE9UcVdGZ1hZZmc0TnBWWDBza2szeUExM2JsZ2pPSURkRm93ckQwQ2dZRUF6dVlvb0FkdXBIZWpKbTNsbjVrMwpxZkgyUjQvNzRGM09aSHVjV1FKTElkd3cyanV4ak03RFFPeEdJZTQ5MDZLSXhINUFGQndPYjM4K0oxZWVCZG9YCjVQbW03Y1NIRXdyQjZxNVRJSVAybk9JYm5UT3FRako5c1k4QXRScDNEeTFTc0l4K0RNT0dXRWJWUEJ6Mko1TzEKZE9Fb0JIcHRvWlNjWEx0UzBTejRkS1E9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: default-http-backend
  labels:
    app: default-http-backend
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: default-http-backend
  template:
    metadata:
      labels:
        app: default-http-backend
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: default-http-backend
        image: gcr.io/google_containers/defaultbackend:1.4
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi
---
apiVersion: v1
kind: Service
metadata:
  name: default-http-backend
  namespace: infra
  labels:
    app: default-http-backend
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: default-http-backend
