---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-issuer
  namespace: infra
spec:
  acme:
    email: amsy810@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-account-key
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: testbed2.amsy.dev
  namespace: infra
spec:
  secretName: testbed-cert
  issuerRef:
    name: letsencrypt-issuer
  dnsNames:
  - testbed2.amsy.dev
  - argocd.amsy.dev
  commonName: testbed2.amsy.dev
