---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: order
  labels:
    service: order
    role: app
spec:
  replicas: 3
  selector:
    matchLabels:
      service: order
      role: app
  template:
    metadata:
      labels:
        service: order
        role: app
    spec:
      containers:
        - name: order
          image: registry-harbor-core.infra.svc.cluster.local/library/order:55399b474d522d7b10938fe971df251458b81c15
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: order
  labels:
    service: order
    role: app
spec:
  type: ClusterIP
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8080
      targetPort: 8080
  selector:
    service: order
    role: app
