---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: order
  namespace: order
  labels:
    service: order
    role: proxy
spec:
  routes:
    - services:
        - name: order
          port: 8080
      permitInsecure: true
