
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: test-topic
  namespace: point
  labels:
    strimzi.io/cluster: point-queue
spec:
  partitions: 1
  replicas: 1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: check-scripts
  namespace: point
  labels:
    service: point
    role: check
data:
  check.sh: |-
    #!/bin/bash
    echo "check script running..."
    echo "This is test message at [$(date)]." | bin/kafka-console-producer.sh --broker-list ${QUEUE_HOST}:${QUEUE_PORT} --topic ${QUEUE_TOPIC}
    bin/kafka-console-consumer.sh --bootstrap-server ${QUEUE_HOST}:${QUEUE_PORT} --topic ${QUEUE_TOPIC} --from-beginning --timeout-ms 10000
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: check-job
  namespace: point
  labels:
    service: point
    role: check
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Replace
  startingDeadlineSeconds: 30
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  suspend: false
  jobTemplate:
    spec:
      completions: 1
      parallelism: 1
      backoffLimit: 10
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: check-container
            image: strimzi/kafka:0.16.2-kafka-2.4.0
            command:
            - /scripts/check.sh
            env:
            - name: QUEUE_HOST
              value: point-queue-kafka-bootstrap.point.svc.cluster.local
            - name: QUEUE_PORT
              value: "9092"
            - name: QUEUE_TOPIC
              value: test-topic
            - name: QUEUE_USER
              value: point-user
            - name: QUEUE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: point-user
                  key: user.password
            volumeMounts:
            - name: scripts-volume
              mountPath: /scripts
          volumes:
            - name: scripts-volume
              configMap:
                name: check-scripts
                defaultMode: 493 # mode 755
