---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: point
  namespace: point
  labels:
    service: point
    role: proxy
spec:
  routes:
    - services:
        - name: point
          port: 8080
      conditions:
        - prefix: /point
      pathRewritePolicy:
        replacePrefix:
          - replacement: /point
      permitInsecure: true
