---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: admin
  labels:
    service: admin
    role: app
spec:
  replicas: 1
  selector:
    matchLabels:
      service: admin
      role: app
  template:
    metadata:
      labels:
        service: admin
        role: app
    spec:
      containers:
        - name: admin
          image: registry-harbor-core.infra.svc.cluster.local/library/admin:55399b474d522d7b10938fe971df251458b81c15
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: admin
  namespace: admin
  labels:
    service: admin
    role: app
spec:
  type: ClusterIP
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8080
      targetPort: 80
  selector:
    service: admin
    role: app
