---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  labels:
    service: product
    role: app
spec:
  replicas: 3
  selector:
    matchLabels:
      service: product
      role: app
  template:
    metadata:
      labels:
        service: product
        role: app
    spec:
      containers:
        - name: product-app
          image: k8stestbed/product:latest
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: product
  labels:
    service: product
    role: app
spec:
  type: ClusterIP
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8080
      targetPort: 8080
  selector:
    service: product
    role: app
