---
apiVersion: v1
kind: ConfigMap
metadata:
  name: check-scripts
  namespace: product
  labels:
    service: product
    role: check
data:
  check.sh: |-
    #!/bin/bash
    echo "check script running..."
    mysql -u ${DB_USERNAME} -p${DB_PASSWORD} -D ${DB_NAME} -h ${DB_HOST} -e "show tables\G"
    mysql -u ${DB_USERNAME} -p${DB_PASSWORD} -D ${DB_NAME} -h ${DB_HOST} -e "show databases\G"
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: check-job
  namespace: product
  labels:
    service: product
    role: check
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Replace
  startingDeadlineSeconds: 30
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  suspend: false
  jobTemplate:
    spec:
      completions: 1
      parallelism: 1
      backoffLimit: 10
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: check-container
            image: mysql:5.7
            command:
            - /scripts/check.sh
            env:
            - name: DB_HOST
              value: product-db-mysql-master.product.svc.cluster.local
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: product-db
                  key: USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: product-db
                  key: PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: product-db
                  key: DATABASE
            volumeMounts:
            - name: scripts-volume
              mountPath: /scripts
          volumes:
            - name: scripts-volume
              configMap:
                name: check-scripts
                defaultMode: 493 # mode 755
