---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: client
  labels:
    service: client
    role: app
spec:
  replicas: 1
  selector:
    matchLabels:
      service: client
      role: app
  template:
    metadata:
      labels:
        service: client
        role: app
    spec:
      containers:
        - name: client
          image: k8stestbed/client:latest
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: client
  labels:
    service: client
    role: app
spec:
  type: ClusterIP
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8080
      targetPort: 80
  selector:
    service: client
    role: app
