---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: product
  namespace: product
  labels:
    service: product
    role: proxy
spec:
  routes:
    - services:
        - name: product
          port: 8080
      permitInsecure: true
