---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: product
  namespace: product
  labels:
    service: product
    role: proxy
spec:
  routes:
    - services:
        - name: product
          port: 8080
      conditions:
        - prefix: /product
      pathRewritePolicy:
        replacePrefix:
          - replacement: /
            prefix: /product
      permitInsecure: true
---
apiVersion: v1
kind: Namespace
metadata:
  name: client
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: client
  namespace: client
  labels:
    service: client
    role: proxy
spec:
  routes:
    - services:
        - name: client
          port: 8080
      permitInsecure: true
