---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: product
  namespace: product
spec:
  routes:
    - services:
        - name: product
          port: 8080
      permitInsecure: true
