---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: search
  namespace: search
  labels:
    service: search
    role: proxy
spec:
  routes:
    - services:
        - name: search
          port: 8080
      permitInsecure: true
